/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Q4CRight.h
**     Project     : Robo
**     Processor   : MK22FX512VLQ12
**     Component   : QuadCounter
**     Version     : Component 01.026, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-04-26, 08:42, # CodeGen: 5
**     Abstract    :
**
This driver implements a quadrature encoder using two signals (C1 and C2) to generate position information.
**     Settings    :
**          Component name                                 : Q4CRight
**          C1 and C2 swapped                              : yes
**          Counter Type                                   : 32bit
**          Method                                         : 
**            Sampling                                     : Enabled
**              Error Correction                           : no
**              C1                                         : Cx
**              C2                                         : Cx
**            Input Capture                                : Disabled
**          Shell                                          : Enabled
**            Shell                                        : CLS1
**            Utility                                      : UTIL1
**     Contents    :
**         GetPos       - Q4CRight_QuadCntrType Q4CRight_GetPos(void);
**         SetPos       - void Q4CRight_SetPos(Q4CRight_QuadCntrType pos);
**         GetVal       - uint8_t Q4CRight_GetVal(void);
**         Sample       - void Q4CRight_Sample(void);
**         NofErrors    - uint16_t Q4CRight_NofErrors(void);
**         Deinit       - void Q4CRight_Deinit(void);
**         Init         - void Q4CRight_Init(void);
**         ParseCommand - uint8_t Q4CRight_ParseCommand(const unsigned char *cmd, bool *handled, const...
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2014, all rights reserved.
**     This an open source software using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Q4CRight.h
** @version 01.00
** @brief
**
This driver implements a quadrature encoder using two signals (C1 and C2) to generate position information.
*/         
/*!
**  @addtogroup Q4CRight_module Q4CRight module documentation
**  @{
*/         

#ifndef __Q4CRight_H
#define __Q4CRight_H

/* MODULE Q4CRight. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "C12.h"
#include "C22.h"
#include "CLS1.h"
#include "UTIL1.h"

#include "Cpu.h"


#define Q4CRight_GET_C1_PIN()      (C12_GetVal())
#define Q4CRight_GET_C2_PIN()      (C22_GetVal())
#define Q4CRight_GET_C1_C2_PINS()  ((Q4CRight_GET_C2_PIN()!=0?2:0)|(Q4CRight_GET_C1_PIN()!=0?1:0))

typedef uint32_t Q4CRight_QuadCntrType;
#define Q4CRight_CNTR_BITS  32
  /*!< Number of bits in counter */

#define Q4CRight_PARSE_COMMAND_ENABLED  1  /* set to 1 if method ParseCommand() is present, 0 otherwise */


void Q4CRight_SetPos(Q4CRight_QuadCntrType pos);
/*
** ===================================================================
**     Method      :  Q4CRight_SetPos (component QuadCounter)
**     Description :
**         Sets the position information. Can be used as well to reset
**         the position information.
**     Parameters  :
**         NAME            - DESCRIPTION
**         pos             - Position value to be set.
**     Returns     : Nothing
** ===================================================================
*/

Q4CRight_QuadCntrType Q4CRight_GetPos(void);
/*
** ===================================================================
**     Method      :  Q4CRight_GetPos (component QuadCounter)
**     Description :
**         Returns the current position based on the encoder tracking.
**     Parameters  : None
**     Returns     :
**         ---             - position
** ===================================================================
*/

void Q4CRight_Sample(void);
/*
** ===================================================================
**     Method      :  Q4CRight_Sample (component QuadCounter)
**     Description :
**         Call this method to periodically sample the signals.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

uint16_t Q4CRight_NofErrors(void);
/*
** ===================================================================
**     Method      :  Q4CRight_NofErrors (component QuadCounter)
**     Description :
**         Returns the number of decoding errors
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void Q4CRight_Deinit(void);
/*
** ===================================================================
**     Method      :  Q4CRight_Deinit (component QuadCounter)
**     Description :
**         Module de-initialization method
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Q4CRight_Init(void);
/*
** ===================================================================
**     Method      :  Q4CRight_Init (component QuadCounter)
**     Description :
**         Module initialization method
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

uint8_t Q4CRight_ParseCommand(const unsigned char *cmd, bool *handled, const CLS1_StdIOType *io);
/*
** ===================================================================
**     Method      :  Q4CRight_ParseCommand (component QuadCounter)
**     Description :
**         Handler to process shell commands
**     Parameters  :
**         NAME            - DESCRIPTION
**         cmd             - Command string to be parsed
**       * handled         - Pointer to boolean. The handler
**                           sets this variable to TRUE if command was
**                           handled, otherwise let it untouched.
**         io              - Pointer to I/O structure
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

#define Q4CRight_GetVal() \
  Q4CRight_GET_C1_C2_PINS()

/*
** ===================================================================
**     Method      :  Q4CRight_GetVal (component QuadCounter)
**     Description :
**         Returns the quadrature value (0, 1, 2 or 3)
**     Parameters  : None
**     Returns     :
**         ---             - Quadrature value (0-3)
** ===================================================================
*/

/* END Q4CRight. */

#endif
/* ifndef __Q4CRight_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
