################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Generated_Code/AS1.c \
../Generated_Code/ASerialLdd1.c \
../Generated_Code/ASerialLdd2.c \
../Generated_Code/BT1.c \
../Generated_Code/BUZ1.c \
../Generated_Code/BitIoLdd1.c \
../Generated_Code/BitIoLdd10.c \
../Generated_Code/BitIoLdd11.c \
../Generated_Code/BitIoLdd12.c \
../Generated_Code/BitIoLdd13.c \
../Generated_Code/BitIoLdd14.c \
../Generated_Code/BitIoLdd15.c \
../Generated_Code/BitIoLdd16.c \
../Generated_Code/BitIoLdd17.c \
../Generated_Code/BitIoLdd18.c \
../Generated_Code/BitIoLdd19.c \
../Generated_Code/BitIoLdd2.c \
../Generated_Code/BitIoLdd4.c \
../Generated_Code/BitIoLdd5.c \
../Generated_Code/BitIoLdd6.c \
../Generated_Code/BitIoLdd7.c \
../Generated_Code/BitIoLdd8.c \
../Generated_Code/BitIoLdd9.c \
../Generated_Code/C11.c \
../Generated_Code/C12.c \
../Generated_Code/C21.c \
../Generated_Code/C22.c \
../Generated_Code/CLS1.c \
../Generated_Code/CS1.c \
../Generated_Code/Cpu.c \
../Generated_Code/DIRL.c \
../Generated_Code/DIRR.c \
../Generated_Code/ExtIntLdd1.c \
../Generated_Code/FRTOS1.c \
../Generated_Code/HF1.c \
../Generated_Code/IR1.c \
../Generated_Code/IR2.c \
../Generated_Code/IR3.c \
../Generated_Code/IR4.c \
../Generated_Code/IR5.c \
../Generated_Code/IR6.c \
../Generated_Code/KSDK1.c \
../Generated_Code/LEDPin1.c \
../Generated_Code/LEDPin2.c \
../Generated_Code/LED_IR.c \
../Generated_Code/LEDpin3.c \
../Generated_Code/MCP4728_LDAC.c \
../Generated_Code/MCP4728_RDY.c \
../Generated_Code/MOTTU.c \
../Generated_Code/PE_LDD.c \
../Generated_Code/PTA.c \
../Generated_Code/PWML.c \
../Generated_Code/PWMR.c \
../Generated_Code/PwmLdd2.c \
../Generated_Code/PwmLdd3.c \
../Generated_Code/Q4CLeft.c \
../Generated_Code/Q4CRight.c \
../Generated_Code/QuadInt.c \
../Generated_Code/RTT1.c \
../Generated_Code/RTT_Syscalls_GCC.c \
../Generated_Code/RefCnt.c \
../Generated_Code/SEGGER_RTT.c \
../Generated_Code/SEGGER_RTT_printf.c \
../Generated_Code/SEGGER_SYSVIEW.c \
../Generated_Code/SEGGER_SYSVIEW_Config.c \
../Generated_Code/SEGGER_SYSVIEW_FreeRTOS.c \
../Generated_Code/SW1.c \
../Generated_Code/SYS1.c \
../Generated_Code/Serial1.c \
../Generated_Code/TU_MCP4728.c \
../Generated_Code/TU_QuadInt.c \
../Generated_Code/TimerIntLdd2.c \
../Generated_Code/UTIL1.c \
../Generated_Code/Vectors.c \
../Generated_Code/WAIT1.c \
../Generated_Code/croutine.c \
../Generated_Code/event_groups.c \
../Generated_Code/heap_1.c \
../Generated_Code/heap_2.c \
../Generated_Code/heap_3.c \
../Generated_Code/heap_4.c \
../Generated_Code/heap_5.c \
../Generated_Code/list.c \
../Generated_Code/port.c \
../Generated_Code/queue.c \
../Generated_Code/tasks.c \
../Generated_Code/timers.c 

OBJS += \
./Generated_Code/AS1.o \
./Generated_Code/ASerialLdd1.o \
./Generated_Code/ASerialLdd2.o \
./Generated_Code/BT1.o \
./Generated_Code/BUZ1.o \
./Generated_Code/BitIoLdd1.o \
./Generated_Code/BitIoLdd10.o \
./Generated_Code/BitIoLdd11.o \
./Generated_Code/BitIoLdd12.o \
./Generated_Code/BitIoLdd13.o \
./Generated_Code/BitIoLdd14.o \
./Generated_Code/BitIoLdd15.o \
./Generated_Code/BitIoLdd16.o \
./Generated_Code/BitIoLdd17.o \
./Generated_Code/BitIoLdd18.o \
./Generated_Code/BitIoLdd19.o \
./Generated_Code/BitIoLdd2.o \
./Generated_Code/BitIoLdd4.o \
./Generated_Code/BitIoLdd5.o \
./Generated_Code/BitIoLdd6.o \
./Generated_Code/BitIoLdd7.o \
./Generated_Code/BitIoLdd8.o \
./Generated_Code/BitIoLdd9.o \
./Generated_Code/C11.o \
./Generated_Code/C12.o \
./Generated_Code/C21.o \
./Generated_Code/C22.o \
./Generated_Code/CLS1.o \
./Generated_Code/CS1.o \
./Generated_Code/Cpu.o \
./Generated_Code/DIRL.o \
./Generated_Code/DIRR.o \
./Generated_Code/ExtIntLdd1.o \
./Generated_Code/FRTOS1.o \
./Generated_Code/HF1.o \
./Generated_Code/IR1.o \
./Generated_Code/IR2.o \
./Generated_Code/IR3.o \
./Generated_Code/IR4.o \
./Generated_Code/IR5.o \
./Generated_Code/IR6.o \
./Generated_Code/KSDK1.o \
./Generated_Code/LEDPin1.o \
./Generated_Code/LEDPin2.o \
./Generated_Code/LED_IR.o \
./Generated_Code/LEDpin3.o \
./Generated_Code/MCP4728_LDAC.o \
./Generated_Code/MCP4728_RDY.o \
./Generated_Code/MOTTU.o \
./Generated_Code/PE_LDD.o \
./Generated_Code/PTA.o \
./Generated_Code/PWML.o \
./Generated_Code/PWMR.o \
./Generated_Code/PwmLdd2.o \
./Generated_Code/PwmLdd3.o \
./Generated_Code/Q4CLeft.o \
./Generated_Code/Q4CRight.o \
./Generated_Code/QuadInt.o \
./Generated_Code/RTT1.o \
./Generated_Code/RTT_Syscalls_GCC.o \
./Generated_Code/RefCnt.o \
./Generated_Code/SEGGER_RTT.o \
./Generated_Code/SEGGER_RTT_printf.o \
./Generated_Code/SEGGER_SYSVIEW.o \
./Generated_Code/SEGGER_SYSVIEW_Config.o \
./Generated_Code/SEGGER_SYSVIEW_FreeRTOS.o \
./Generated_Code/SW1.o \
./Generated_Code/SYS1.o \
./Generated_Code/Serial1.o \
./Generated_Code/TU_MCP4728.o \
./Generated_Code/TU_QuadInt.o \
./Generated_Code/TimerIntLdd2.o \
./Generated_Code/UTIL1.o \
./Generated_Code/Vectors.o \
./Generated_Code/WAIT1.o \
./Generated_Code/croutine.o \
./Generated_Code/event_groups.o \
./Generated_Code/heap_1.o \
./Generated_Code/heap_2.o \
./Generated_Code/heap_3.o \
./Generated_Code/heap_4.o \
./Generated_Code/heap_5.o \
./Generated_Code/list.o \
./Generated_Code/port.o \
./Generated_Code/queue.o \
./Generated_Code/tasks.o \
./Generated_Code/timers.o 

C_DEPS += \
./Generated_Code/AS1.d \
./Generated_Code/ASerialLdd1.d \
./Generated_Code/ASerialLdd2.d \
./Generated_Code/BT1.d \
./Generated_Code/BUZ1.d \
./Generated_Code/BitIoLdd1.d \
./Generated_Code/BitIoLdd10.d \
./Generated_Code/BitIoLdd11.d \
./Generated_Code/BitIoLdd12.d \
./Generated_Code/BitIoLdd13.d \
./Generated_Code/BitIoLdd14.d \
./Generated_Code/BitIoLdd15.d \
./Generated_Code/BitIoLdd16.d \
./Generated_Code/BitIoLdd17.d \
./Generated_Code/BitIoLdd18.d \
./Generated_Code/BitIoLdd19.d \
./Generated_Code/BitIoLdd2.d \
./Generated_Code/BitIoLdd4.d \
./Generated_Code/BitIoLdd5.d \
./Generated_Code/BitIoLdd6.d \
./Generated_Code/BitIoLdd7.d \
./Generated_Code/BitIoLdd8.d \
./Generated_Code/BitIoLdd9.d \
./Generated_Code/C11.d \
./Generated_Code/C12.d \
./Generated_Code/C21.d \
./Generated_Code/C22.d \
./Generated_Code/CLS1.d \
./Generated_Code/CS1.d \
./Generated_Code/Cpu.d \
./Generated_Code/DIRL.d \
./Generated_Code/DIRR.d \
./Generated_Code/ExtIntLdd1.d \
./Generated_Code/FRTOS1.d \
./Generated_Code/HF1.d \
./Generated_Code/IR1.d \
./Generated_Code/IR2.d \
./Generated_Code/IR3.d \
./Generated_Code/IR4.d \
./Generated_Code/IR5.d \
./Generated_Code/IR6.d \
./Generated_Code/KSDK1.d \
./Generated_Code/LEDPin1.d \
./Generated_Code/LEDPin2.d \
./Generated_Code/LED_IR.d \
./Generated_Code/LEDpin3.d \
./Generated_Code/MCP4728_LDAC.d \
./Generated_Code/MCP4728_RDY.d \
./Generated_Code/MOTTU.d \
./Generated_Code/PE_LDD.d \
./Generated_Code/PTA.d \
./Generated_Code/PWML.d \
./Generated_Code/PWMR.d \
./Generated_Code/PwmLdd2.d \
./Generated_Code/PwmLdd3.d \
./Generated_Code/Q4CLeft.d \
./Generated_Code/Q4CRight.d \
./Generated_Code/QuadInt.d \
./Generated_Code/RTT1.d \
./Generated_Code/RTT_Syscalls_GCC.d \
./Generated_Code/RefCnt.d \
./Generated_Code/SEGGER_RTT.d \
./Generated_Code/SEGGER_RTT_printf.d \
./Generated_Code/SEGGER_SYSVIEW.d \
./Generated_Code/SEGGER_SYSVIEW_Config.d \
./Generated_Code/SEGGER_SYSVIEW_FreeRTOS.d \
./Generated_Code/SW1.d \
./Generated_Code/SYS1.d \
./Generated_Code/Serial1.d \
./Generated_Code/TU_MCP4728.d \
./Generated_Code/TU_QuadInt.d \
./Generated_Code/TimerIntLdd2.d \
./Generated_Code/UTIL1.d \
./Generated_Code/Vectors.d \
./Generated_Code/WAIT1.d \
./Generated_Code/croutine.d \
./Generated_Code/event_groups.d \
./Generated_Code/heap_1.d \
./Generated_Code/heap_2.d \
./Generated_Code/heap_3.d \
./Generated_Code/heap_4.d \
./Generated_Code/heap_5.d \
./Generated_Code/list.d \
./Generated_Code/port.d \
./Generated_Code/queue.d \
./Generated_Code/tasks.d \
./Generated_Code/timers.d 


# Each subdirectory must supply rules for building sources it contributes
Generated_Code/%.o: ../Generated_Code/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g3 -I"/Users/Florian/Desktop/Studium/6.Semester/INTRO/KDS/Robo/Static_Code/PDD" -I"/Users/Florian/Desktop/Studium/6.Semester/INTRO/KDS/Robo/Static_Code/IO_Map" -I"/Users/Florian/Desktop/Studium/6.Semester/INTRO/KDS/Robo/Sources" -I"/Users/Florian/Desktop/Studium/6.Semester/INTRO/KDS/Robo/Generated_Code" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


